_BASE_: video_mask2former_R50_cls_agnostic.yaml
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.00002
  STEPS: (39999,)
  MAX_ITER: 40000
  CHECKPOINT_PERIOD: 500000
# DATALOADER:
#   COPY_PASTE: False

DATASETS:
  # TRAIN: ("davis_train", "imagenet_video_train_cls_agnostic")
  # TRAIN: ("davis_train", )
  # TRAIN: ("davis_val_inference", )
  # TRAIN: ("davis_inf_test", )
  # TRAIN: ("ytvis_2019_train_new", )
  # TRAIN: ("ytvis_test",)
  # TRAIN: ("ytvis_test", "ytvis_2019_train_new")
  # TRAIN: ("ytvis_2019_small", "ytvis_2019_val_30")
  # TRAIN: ("ytvis_2019_small", )
  TRAIN: ("ytvis_s025iouf_allnf_cn075_adding_refresh_g2_b4", "imagenet_video_train_cls_agnostic")
  # TEST: ("davis_val_half", "davis_train_half")
  # TEST: ("ytvis_2019_val_new", "ytvis_2019_small")
  # TEST: ("ytvis_2019_val_30", "ytvis_2019_small" )
  TEST: ("ytvis_2019_train_new", "ytvis_2019_val_new")
  # TEST: ("ytvis_2019_val_30", "ytvis_2019_small" )
  # TEST: ("tmp", "ytvis_2019_small" )
TEST:
  EVAL_PERIOD: 10000
MODEL_NAME: "ytvis_s025iouf_allnf_cn075_adding_refresh_g2_b4"
# OUTPUT_RAW_MASKS: True
# OUTPUT_IOUS: True
OUTPUT_MASKIOUS: True
USE_DROPLOSS: True
# LABEL_DROPLOSS: True
# LOSS_MASKIOU_ALL: True
FREEZE_MASKIOU: True